### PR TITLE
Add BoxPlotSeries examples

### PR DESCRIPTION
**Pull request by Peter-B-**
Hello,

I found that the documentation does not contain a BoxPlot example. So I added two files. The example was taken from the OxyPlot repository. I hope that is OK.

### CODE REVIEW

**Comment by Peter-B-** [comment]
I see there are great examples in the ExampleLibrary directory of the oxyplot repository. Does it make sense to have some of them for the docs in a separate directory? 

Another option might be to mark some of those examples for export as image. We could use the ExportAttribute, like in the oxyplot/ducumentation-examples repository and have an extra export project there.

That way the documentation examples would also stay up to date during refactorings.

**Comment by objorke** [comment]
Yes, it could be a good idea to merge the ExampleLibrary and documentation-examples! The ExampleGenerator could read the models from the ExampleLibrary filtering by a new attribute, e.g. `[DocumentationExample]`.

**Comment by Peter-B-** [comment]
So I will try to add ```[DocumentationExample]``` to the oyxplot examples. 

I will also move the ExampleGenerator project over to that repository. Or do you think it makes sense to keep this project in this separate github project?

**Comment by Peter-B-** [comment]
I think this PR is obsolete. The ExampleGenerator is now part of the oxyplot repository.

**Pull request closed without merging**
